import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import 'react-tabs/style/react-tabs.css';
import 'lightbox.js-react/dist/index.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce Project Fastion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="../assets/images/favicon/1.png" type="image/x-icon" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/font-awesome.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/animate.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/themify-icons.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/vendors/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="../assets/css/style.css" />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
