import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata = {
    title: "Frontend E-commerce Project",
    description: "Generated by create next app",
};

export default function FrontendLayout({ children }) {
    return (
        <>
            <Header />
            {children}
            <Footer />
        </>
    );
}
