import AdminFooter from "@/components/backend/Footer";
import AdminHeader from "@/components/backend/Header";
import Sidebar from "@/components/backend/Sidebar";


export const metadata = {
    title: "Backend E-commerce Project",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" type="text/css" href="../assets/css/admin.css" />
            </head>
            <body>
                <div className="page-wrapper">
                    <AdminHeader />

                    <div className="page-body-wrapper">
                        <Sidebar />
                        {children}
                        <AdminFooter />
                    </div>
                </div>
            </body>
        </html >
    );
}
